"""
Agent 3: Critic / Validator Agent
Reviews the generated playbook before showing it to the user.
Flags dangerous steps, checks for missing critical phases, and validates
coverage against MITRE ATT&CK response techniques.

This is the key differentiator from a static playbook — the critic catches
issues before a responder acts on bad advice during a live incident.
"""
# Developed with AI assistance (Claude)

import json
import logging
from langchain_core.messages import HumanMessage

from config.settings import get_llm, ORG_NAME
from agents.state import AgentState

logger = logging.getLogger(__name__)

CRITIC_PROMPT = """You are a senior incident response expert reviewing a playbook generated by a junior analyst.
Your job is to catch dangerous steps, missing critical actions, and gaps before a responder executes this plan
during a live incident for {org_name}.

Organization context:
{org_context}

Incident:
- Type: {incident_type}
- Severity: {severity}
- Affected Systems: {affected_systems}

Playbook to review:
{playbook_json}

Review the playbook critically. Check for:

1. DANGEROUS STEPS — actions that could make the incident worse:
   - Powering off a system before forensic memory capture (destroys evidence)
   - Wiping/reimaging before forensic imaging (destroys evidence)
   - Disabling a shared account that active users rely on (e.g., clinical staff on Epic EHR)
   - Notifying a vendor or suspect before forensics are complete (alerting an insider)
   - Restoring from a backup that may itself be compromised
   - Patching without change management in a production healthcare environment

2. MISSING STEPS — critical actions absent from the playbook:
   - No forensic evidence preservation step
   - No HIPAA breach risk assessment for healthcare incidents
   - No stakeholder notification (IT Director, COO, legal)
   - No verification of backup integrity before restoring
   - No monitoring/watchlist after recovery
   - No chain of custody documentation for evidence

3. ORG-SPECIFIC GAPS — given this organization's known limitations:
   - No SIEM means no centralized log access — steps requiring log review need alternatives
   - No EDR means antivirus-only scanning — limits malware detection
   - No PAM tool — privileged access steps need manual workarounds
   - 35% MFA coverage — account disable steps may need broader scope

For each issue found, provide:
- issue: Description of the problem
- severity: "Blocking" (must fix before use) | "Warning" (should fix) | "Advisory" (nice to have)
- affected_step: Which step/phase it affects
- recommendation: Specific fix

Also provide:
- approved: true if no Blocking issues found, false if any Blocking issues exist
- revised_notes: 1-2 sentences of overall feedback for the playbook generator

Return JSON:
{{
  "issues": [
    {{
      "issue": "...",
      "severity": "Blocking|Warning|Advisory",
      "affected_step": "Phase X, Step Y",
      "recommendation": "..."
    }}
  ],
  "approved": true,
  "revised_notes": "..."
}}

If the playbook is solid with no issues, return an empty issues array and approved: true.
Return only valid JSON:"""


REVISION_PROMPT = """You are an incident response expert. A critic has reviewed a playbook and identified issues.
Apply the critic's recommendations to produce an improved playbook.

Original playbook:
{playbook_json}

Critic issues to address:
{issues_json}

Revised notes from critic:
{revised_notes}

Produce an improved playbook that:
1. Fixes all Blocking issues
2. Addresses Warning issues where possible
3. Maintains the same JSON structure as the original

Return the same JSON structure as the original playbook (playbook_phases array with steps).
Return only valid JSON:"""


def run_critic_node(state: AgentState) -> AgentState:
    """LangGraph node for the Critic / Validator Agent."""
    logger.info("Critic Agent: Reviewing playbook for dangerous or missing steps")
    state["current_step"] = "critic"
    state["progress_messages"] = state.get("progress_messages", [])
    state["progress_messages"].append("Critic Agent: Reviewing playbook for issues...")

    try:
        llm = get_llm()
        playbook_json = json.dumps(state.get("playbook_phases", []), indent=2)

        # Step 1: Review the playbook
        review_prompt = CRITIC_PROMPT.format(
            org_name=state.get("org_name", ORG_NAME),
            org_context=state.get("org_context", ""),
            incident_type=state.get("incident_type", "unknown"),
            severity=state.get("severity", "High"),
            affected_systems=", ".join(state.get("affected_systems", [])),
            playbook_json=playbook_json,
        )
        review_response = llm.invoke([HumanMessage(content=review_prompt)])
        review_data = _parse_review(review_response.content)

        state["critic_issues"] = review_data.get("issues", [])
        state["critic_approved"] = review_data.get("approved", True)

        blocking = [i for i in state["critic_issues"] if i.get("severity") == "Blocking"]
        warnings = [i for i in state["critic_issues"] if i.get("severity") == "Warning"]

        state["progress_messages"].append(
            f"Critic Agent: Found {len(blocking)} blocking issues, {len(warnings)} warnings"
        )

        # Step 2: If blocking issues, revise the playbook
        if blocking:
            logger.info(f"Critic found {len(blocking)} blocking issues — requesting revision")
            state["progress_messages"].append("Critic Agent: Revising playbook to fix blocking issues...")

            revision_prompt = REVISION_PROMPT.format(
                playbook_json=playbook_json,
                issues_json=json.dumps(state["critic_issues"], indent=2),
                revised_notes=review_data.get("revised_notes", ""),
            )
            revision_response = llm.invoke([HumanMessage(content=revision_prompt)])
            revised_phases = _parse_revised_playbook(revision_response.content)
            state["revised_playbook_phases"] = revised_phases if revised_phases else state["playbook_phases"]
        else:
            state["revised_playbook_phases"] = state["playbook_phases"]

        fallback_flags = state.get("fallback_flags") or {}
        fallback_flags["critic"] = "llm_generated"
        state["fallback_flags"] = fallback_flags

        state["progress_messages"].append("Critic Agent: Review complete ✓")
        logger.info(f"Critic complete: approved={state['critic_approved']}, "
                    f"issues={len(state['critic_issues'])}")

    except Exception as e:
        logger.error(f"Critic Agent error: {e}")
        state["errors"] = state.get("errors", []) + [f"Critic Agent: {str(e)}"]
        state["critic_issues"] = state.get("critic_issues") or []
        state["critic_approved"] = True
        state["revised_playbook_phases"] = state.get("revised_playbook_phases") or state.get("playbook_phases") or []
        fallback_flags = state.get("fallback_flags") or {}
        fallback_flags["critic"] = "fallback_static"
        state["fallback_flags"] = fallback_flags

    return state


def _parse_review(content: str) -> dict:
    try:
        content = content.strip()
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
        start = content.find("{")
        end = content.rfind("}") + 1
        if start >= 0 and end > start:
            return json.loads(content[start:end])
    except Exception as e:
        logger.warning(f"Critic review parse failed: {e}")
    return {"issues": [], "approved": True, "revised_notes": ""}


def _parse_revised_playbook(content: str) -> list:
    try:
        content = content.strip()
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
        # Could be wrapped in {"playbook_phases": [...]} or just [...]
        if content.startswith("{"):
            data = json.loads(content)
            return data.get("playbook_phases", [])
        elif content.startswith("["):
            return json.loads(content)
    except Exception as e:
        logger.warning(f"Revised playbook parse failed: {e}")
    return []
